// Single source of truth for brand info used across Home and Products pages.
// Translatable fields are keyed by locale (en/hi/mr). Non-text fields
// (slug, logo, accent, images, swatch colors) are shared across locales.
// Use getBrands(locale) to get a flat, locale-resolved array like before.

const PLACEHOLDER_DETAILS = {
  fitNotes: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric composition, available sizes, fit notes, colourways, and minimum order quantity for wholesale buyers.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक संरचना, उपलब्ध साइज़, फ़िट नोट्स, रंग विकल्प, और थोक खरीदारों के लिए न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिक रचना, उपलब्ध साइज, फिट नोट्स, रंगपर्याय आणि घाऊक खरेदीदारांसाठी किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  packSizes: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric composition, available sizes, pack sizes, colourways, and minimum order quantity for wholesale buyers.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक संरचना, उपलब्ध साइज़, पैक साइज़, रंग विकल्प, और थोक खरीदारों के लिए न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिक रचना, उपलब्ध साइज, पॅक साइज, रंगपर्याय आणि घाऊक खरेदीदारांसाठी किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  sizeRange: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric composition, size range, fit notes, colourways, and minimum order quantity for wholesale buyers.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक संरचना, साइज़ रेंज, फ़िट नोट्स, रंग विकल्प, और थोक खरीदारों के लिए न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिक रचना, साइज रेंज, फिट नोट्स, रंगपर्याय आणि घाऊक खरेदीदारांसाठी किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  softnessAge: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric softness, age/size range, colourways, and minimum order quantity for wholesale buyers.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक की कोमलता, आयु/साइज़ रेंज, रंग विकल्प, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिकची मऊपणा, वय/साइज रेंज, रंगपर्याय आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  fabricBlend: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric blend, size range, pack sizes, colourways, and minimum order quantity for wholesale buyers.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक ब्लेंड, साइज़ रेंज, पैक साइज़, रंग विकल्प, और थोक खरीदारों के लिए न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिक ब्लेंड, साइज रेंज, पॅक साइज, रंगपर्याय आणि घाऊक खरेदीदारांसाठी किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  blendSimple: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric blend, size range, colourways, and minimum order quantity.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक ब्लेंड, साइज़ रेंज, रंग विकल्प, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिक ब्लेंड, साइज रेंज, रंगपर्याय आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  stretchAge: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric stretch, age/size range, colourways, and minimum order quantity.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक की स्ट्रेच क्षमता, आयु/साइज़ रेंज, रंग विकल्प, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिकची स्ट्रेच क्षमता, वय/साइज रेंज, रंगपर्याय आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  packComposition: {
    en: "Placeholder detail copy — replace with real specs. Typically covers pack composition, fabric blend, sizes, and minimum order quantity.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें पैक संरचना, फ़ैब्रिक ब्लेंड, साइज़, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा पॅक रचना, फॅब्रिक ब्लेंड, साइज आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  cushioningPack: {
    en: "Placeholder detail copy — replace with real specs. Typically covers cushioning, pack sizes, colourways, and minimum order quantity.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें कुशनिंग, पैक साइज़, रंग विकल्प, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा कुशनिंग, पॅक साइज, रंगपर्याय आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  insulation: {
    en: "Placeholder detail copy — replace with real specs. Typically covers insulation type, fabric blend, sizes, and minimum order quantity.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें इंसुलेशन प्रकार, फ़ैब्रिक ब्लेंड, साइज़, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा इन्सुलेशन प्रकार, फॅब्रिक ब्लेंड, साइज आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
  softnessAgeNoColour: {
    en: "Placeholder detail copy — replace with real specs. Typically covers fabric softness, age/size range, and minimum order quantity.",
    hi: "प्लेसहोल्डर विवरण — असली स्पेसिफिकेशन से बदलें। आमतौर पर इसमें फ़ैब्रिक की कोमलता, आयु/साइज़ रेंज, और न्यूनतम ऑर्डर मात्रा शामिल होती है।",
    mr: "प्लेसहोल्डर तपशील — खऱ्या स्पेसिफिकेशन्सने बदला. यामध्ये सहसा फॅब्रिकची मऊपणा, वय/साइज रेंज आणि किमान ऑर्डर प्रमाण यांचा समावेश असतो.",
  },
};

const BRANDS_RAW = [
  {
    slug: "milton",
    name: "Milton",
    logo: null,
    accent: "#003B89",
    segment: { en: "Everyday essentials", hi: "रोज़मर्रा की ज़रूरी चीज़ें", mr: "रोजच्या गरजेच्या वस्तू" },
    status: { en: "Established", hi: "स्थापित", mr: "स्थापित" },
    statusDetail: { en: "Established 1973", hi: "1973 से स्थापित", mr: "1973 पासून स्थापित" },
    homeBlurb: {
      en: "Everyday essentials — the line we started with in 1973.",
      hi: "रोज़मर्रा की ज़रूरी चीज़ें — वह लाइन जिससे हमने 1973 में शुरुआत की थी।",
      mr: "रोजच्या गरजेच्या वस्तू — 1973 मध्ये आम्ही याच लाइनने सुरुवात केली होती.",
    },
    description: {
      en: "Our original line, and still the foundation of the business — everyday hosiery and innerwear essentials, built for reliability over trend cycles.",
      hi: "हमारी मूल लाइन, जो आज भी व्यवसाय की नींव है — रोज़मर्रा की होज़री और इननरवियर ज़रूरतें, जो ट्रेंड से ज़्यादा भरोसेमंद बनी रहने के लिए बनाई गई हैं।",
      mr: "आमची मूळ लाइन, जी आजही व्यवसायाचा पाया आहे — रोजच्या होजिअरी आणि इनरवेअर गरजा, ट्रेंडपेक्षा विश्वासार्हतेसाठी घडवलेल्या.",
    },
    products: [
      {
        name: { en: "Nylon trunks", hi: "नायलॉन ट्रंक्स", mr: "नायलॉन ट्रंक्स" },
        description: {
          en: "The product Milton started with. Classic fit, everyday wear.",
          hi: "वह उत्पाद जिससे Milton की शुरुआत हुई। क्लासिक फ़िट, रोज़मर्रा पहनने के लिए।",
          mr: "ज्या उत्पादनापासून Milton ची सुरुवात झाली. क्लासिक फिट, रोजच्या वापरासाठी.",
        },
        details: PLACEHOLDER_DETAILS.fitNotes,
        swatchA: "#e4edfb",
        swatchB: "#b9d0f2",
      },
      {
        name: { en: "Vests", hi: "बनियान", mr: "बनियन" },
        description: {
          en: "Everyday innerwear staple, sold across general trade.",
          hi: "रोज़मर्रा का इननरवियर स्टेपल, जनरल ट्रेड में बिकता है।",
          mr: "रोजच्या वापरातील इनरवेअर, जनरल ट्रेडमध्ये विकले जाते.",
        },
        details: PLACEHOLDER_DETAILS.fitNotes,
        swatchA: "#e4edfb",
        swatchB: "#b9d0f2",
      },
      {
        name: { en: "Everyday socks", hi: "रोज़मर्रा के मोज़े", mr: "रोजचे मोजे" },
        description: {
          en: "Value-tier hosiery for daily wear.",
          hi: "रोज़ पहनने के लिए वैल्यू-टियर होज़री।",
          mr: "रोजच्या वापरासाठी व्हॅल्यू-टियर होजिअरी.",
        },
        details: PLACEHOLDER_DETAILS.packSizes,
        swatchA: "#e4edfb",
        swatchB: "#b9d0f2",
      },
    ],
  },
  {
    slug: "anicy",
    name: "ANICY",
    logo: "/logos/anicy.png",
    accent: "#0C2C55",
    segment: { en: "Men's performance wear", hi: "मेन्स परफॉर्मेंस वियर", mr: "मेन्स परफॉर्मन्स वेअर" },
    status: { en: "Active", hi: "सक्रिय", mr: "सक्रिय" },
    statusDetail: { en: "Leading brand", hi: "अग्रणी ब्रांड", mr: "आघाडीचा ब्रँड" },
    homeBlurb: {
      en: "Men's performance wear. Our leading brand today.",
      hi: "मेन्स परफॉर्मेंस वियर। आज हमारा अग्रणी ब्रांड।",
      mr: "मेन्स परफॉर्मन्स वेअर. आजचा आमचा आघाडीचा ब्रँड.",
    },
    description: {
      en: "Our leading and most established growth brand — performance-oriented menswear designed for daily activity, sold through general and modern trade.",
      hi: "हमारा अग्रणी और सबसे स्थापित ग्रोथ ब्रांड — रोज़मर्रा की गतिविधि के लिए डिज़ाइन किया गया परफॉर्मेंस-ओरिएंटेड मेन्सवियर, जनरल और मॉडर्न ट्रेड के ज़रिए बेचा जाता है।",
      mr: "आमचा आघाडीचा आणि सर्वात स्थापित ग्रोथ ब्रँड — रोजच्या हालचालींसाठी डिझाइन केलेले परफॉर्मन्स-ओरिएंटेड मेन्सवेअर, जनरल आणि मॉडर्न ट्रेडमार्फत विकले जाते.",
    },
    products: [
      {
        name: { en: "4-Way Track Pant", hi: "4-वे ट्रैक पैंट", mr: "4-वे ट्रॅक पँट" },
        description: {
          en: "A versatile full-length track pant with a clean athletic silhouette, elasticated drawstring waist and practical side pockets.",
          hi: "एक बहुउपयोगी फ़ुल-लेंथ ट्रैक पैंट, साफ़ एथलेटिक सिल्हूट, इलास्टिक ड्रॉस्ट्रिंग कमर और प्रैक्टिकल साइड पॉकेट्स के साथ।",
          mr: "एक बहुउपयोगी फुल-लेंथ ट्रॅक पँट, स्वच्छ अ‍ॅथलेटिक सिल्हूट, इलास्टिक ड्रॉस्ट्रिंग कंबर आणि व्यावहारिक साइड पॉकेट्ससह.",
        },
        details: {
          en: "A versatile full-length track pant with a clean athletic silhouette, elasticated drawstring waist and practical side pockets. Designed with a streamlined fit that works equally well for workouts, running and everyday activewear.",
          hi: "एक बहुउपयोगी फ़ुल-लेंथ ट्रैक पैंट, साफ़ एथलेटिक सिल्हूट, इलास्टिक ड्रॉस्ट्रिंग कमर और प्रैक्टिकल साइड पॉकेट्स के साथ। एक स्ट्रीमलाइन्ड फ़िट के साथ डिज़ाइन की गई जो वर्कआउट, रनिंग और रोज़मर्रा की एक्टिववियर के लिए समान रूप से अच्छी तरह काम करती है।",
          mr: "एक बहुउपयोगी फुल-लेंथ ट्रॅक पँट, स्वच्छ अ‍ॅथलेटिक सिल्हूट, इलास्टिक ड्रॉस्ट्रिंग कंबर आणि व्यावहारिक साइड पॉकेट्ससह. वर्कआउट, धावणे आणि रोजच्या अ‍ॅक्टिव्हवेअरसाठी सारखेच चांगले काम करणाऱ्या स्ट्रीमलाइन्ड फिटसह डिझाइन केलेली.",
        },
        images: ["/products/anicy/1/1.jpg", "/products/anicy/1/2.jpg", "/products/anicy/1/3.jpg", "/products/anicy/1/4.jpg", "/products/anicy/1/5.jpg", "/products/anicy/1/6.jpg"],
      },
      {
        name: { en: "4-Way Bermuda", hi: "4-वे बरमूडा", mr: "4-वे बर्म्युडा" },
        description: {
          en: "A clean athletic bermuda with a relaxed knee-length profile, elastic drawstring waistband and secure zippered side pocket.",
          hi: "एक साफ़ एथलेटिक बरमूडा, आरामदायक नी-लेंथ प्रोफ़ाइल, इलास्टिक ड्रॉस्ट्रिंग कमरबंद और सुरक्षित ज़िप वाली साइड पॉकेट के साथ।",
          mr: "एक स्वच्छ अ‍ॅथलेटिक बर्म्युडा, आरामदायक नी-लेंथ प्रोफाइल, इलास्टिक ड्रॉस्ट्रिंग कंबरपट्टा आणि सुरक्षित झिप असलेल्या साइड पॉकेटसह.",
        },
        details: {
          en: "A clean athletic bermuda with a relaxed knee-length profile, elastic drawstring waistband and secure zippered side pocket. Its lightweight-looking construction makes it ideal for training, sports and casual outdoor wear.",
          hi: "एक साफ़ एथलेटिक बरमूडा, आरामदायक नी-लेंथ प्रोफ़ाइल, इलास्टिक ड्रॉस्ट्रिंग कमरबंद और सुरक्षित ज़िप वाली साइड पॉकेट के साथ। इसकी हल्की बनावट इसे ट्रेनिंग, स्पोर्ट्स और कैज़ुअल आउटडोर वियर के लिए आदर्श बनाती है।",
          mr: "एक स्वच्छ अ‍ॅथलेटिक बर्म्युडा, आरामदायक नी-लेंथ प्रोफाइल, इलास्टिक ड्रॉस्ट्रिंग कंबरपट्टा आणि सुरक्षित झिप असलेल्या साइड पॉकेटसह. याची हलकी रचना ट्रेनिंग, स्पोर्ट्स आणि कॅज्युअल आउटडोअर वापरासाठी आदर्श बनवते.",
        },
        images: ["/products/anicy/2/1.jpg", "/products/anicy/2/2.jpg", "/products/anicy/2/3.jpg", "/products/anicy/2/4.jpg", "/products/anicy/2/5.jpg"],
      },
      {
        name: { en: "4-Way Imported Track Pant — Belt Elastic", hi: "4-वे इम्पोर्टेड ट्रैक पैंट — बेल्ट इलास्टिक", mr: "4-वे इम्पोर्टेड ट्रॅक पँट — बेल्ट इलास्टिक" },
        description: {
          en: "A sleek tapered track pant featuring a structured elastic waistband, side pockets and a minimal athletic finish.",
          hi: "एक स्लीक टेपर्ड ट्रैक पैंट, स्ट्रक्चर्ड इलास्टिक कमरबंद, साइड पॉकेट्स और मिनिमल एथलेटिक फ़िनिश के साथ।",
          mr: "एक स्लीक टेपर्ड ट्रॅक पँट, स्ट्रक्चर्ड इलास्टिक कंबरपट्टा, साइड पॉकेट्स आणि मिनिमल अ‍ॅथलेटिक फिनिशसह.",
        },
        details: {
          en: "A sleek tapered track pant featuring a structured elastic waistband, side pockets and a minimal athletic finish. The smooth surface and narrow-leg silhouette give it a more refined performance look.",
          hi: "एक स्लीक टेपर्ड ट्रैक पैंट, स्ट्रक्चर्ड इलास्टिक कमरबंद, साइड पॉकेट्स और मिनिमल एथलेटिक फ़िनिश के साथ। इसकी स्मूद सतह और नैरो-लेग सिल्हूट इसे एक बेहतर रिफ़ाइंड परफॉर्मेंस लुक देते हैं।",
          mr: "एक स्लीक टेपर्ड ट्रॅक पँट, स्ट्रक्चर्ड इलास्टिक कंबरपट्टा, साइड पॉकेट्स आणि मिनिमल अ‍ॅथलेटिक फिनिशसह. याची गुळगुळीत पृष्ठभाग आणि नॅरो-लेग सिल्हूट यामुळे याला अधिक रिफाइंड परफॉर्मन्स लुक मिळतो.",
        },
        images: ["/products/anicy/3/1.jpg", "/products/anicy/3/2.jpg", "/products/anicy/3/3.jpg", "/products/anicy/3/4.jpg", "/products/anicy/3/5.jpg", "/products/anicy/3/6.jpg"],
      },
      {
        name: { en: "4-Way Imported Track Pant — Machine Elastic", hi: "4-वे इम्पोर्टेड ट्रैक पैंट — मशीन इलास्टिक", mr: "4-वे इम्पोर्टेड ट्रॅक पँट — मशीन इलास्टिक" },
        description: {
          en: "A streamlined tapered track pant with a comfortable gathered waistband, practical zippered side pockets and a clean low-profile finish.",
          hi: "एक स्ट्रीमलाइन्ड टेपर्ड ट्रैक पैंट, आरामदायक गैदर्ड कमरबंद, प्रैक्टिकल ज़िप साइड पॉकेट्स और साफ़ लो-प्रोफ़ाइल फ़िनिश के साथ।",
          mr: "एक स्ट्रीमलाइन्ड टेपर्ड ट्रॅक पँट, आरामदायक गॅदर्ड कंबरपट्टा, व्यावहारिक झिप साइड पॉकेट्स आणि स्वच्छ लो-प्रोफाइल फिनिशसह.",
        },
        details: {
          en: "A streamlined tapered track pant with a comfortable gathered waistband, practical zippered side pockets and a clean low-profile finish. Built for an understated sporty look that transitions easily from training to everyday wear.",
          hi: "एक स्ट्रीमलाइन्ड टेपर्ड ट्रैक पैंट, आरामदायक गैदर्ड कमरबंद, प्रैक्टिकल ज़िप साइड पॉकेट्स और साफ़ लो-प्रोफ़ाइल फ़िनिश के साथ। यह एक सिंपल स्पोर्टी लुक के लिए बनाई गई है जो ट्रेनिंग से रोज़मर्रा पहनने तक आसानी से ढल जाती है।",
          mr: "एक स्ट्रीमलाइन्ड टेपर्ड ट्रॅक पँट, आरामदायक गॅदर्ड कंबरपट्टा, व्यावहारिक झिप साइड पॉकेट्स आणि स्वच्छ लो-प्रोफाइल फिनिशसह. ट्रेनिंगपासून रोजच्या वापरापर्यंत सहज बदलणाऱ्या साध्या स्पोर्टी लुकसाठी ही घडवलेली आहे.",
        },
        images: ["/products/anicy/4/1.jpg", "/products/anicy/4/2.jpg", "/products/anicy/4/3.jpg", "/products/anicy/4/4.jpg", "/products/anicy/4/5.jpg", "/products/anicy/4/6.jpg"],
      },
      {
        name: { en: "4-Way Imported Bermuda", hi: "4-वे इम्पोर्टेड बरमूडा", mr: "4-वे इम्पोर्टेड बर्म्युडा" },
        description: {
          en: "A modern athletic bermuda with a relaxed fit, elastic drawstring waist and deep side pockets.",
          hi: "एक मॉडर्न एथलेटिक बरमूडा, आरामदायक फ़िट, इलास्टिक ड्रॉस्ट्रिंग कमर और गहरी साइड पॉकेट्स के साथ।",
          mr: "एक आधुनिक अ‍ॅथलेटिक बर्म्युडा, आरामदायक फिट, इलास्टिक ड्रॉस्ट्रिंग कंबर आणि खोल साइड पॉकेट्ससह.",
        },
        details: {
          en: "A modern athletic bermuda with a relaxed fit, elastic drawstring waist and deep side pockets. Its clean styling and flexible silhouette make it suitable for gym sessions, outdoor activities and everyday casual wear.",
          hi: "एक मॉडर्न एथलेटिक बरमूडा, आरामदायक फ़िट, इलास्टिक ड्रॉस्ट्रिंग कमर और गहरी साइड पॉकेट्स के साथ। इसकी साफ़ स्टाइलिंग और फ्लेक्सिबल सिल्हूट इसे जिम सेशन, आउटडोर एक्टिविटी और रोज़मर्रा कैज़ुअल वियर के लिए उपयुक्त बनाते हैं।",
          mr: "एक आधुनिक अ‍ॅथलेटिक बर्म्युडा, आरामदायक फिट, इलास्टिक ड्रॉस्ट्रिंग कंबर आणि खोल साइड पॉकेट्ससह. याची स्वच्छ स्टाइलिंग आणि लवचिक सिल्हूट यामुळे हे जिम सेशन्स, आउटडोअर अ‍ॅक्टिव्हिटीज आणि रोजच्या कॅज्युअल वापरासाठी योग्य ठरते.",
        },
        images: ["/products/anicy/5/1.jpg", "/products/anicy/5/2.jpg", "/products/anicy/5/3.jpg", "/products/anicy/5/4.jpg", "/products/anicy/5/5.jpg"],
      },
      {
        name: { en: "4-Way Heavy Track Pant — Belt Elastic", hi: "4-वे हैवी ट्रैक पैंट — बेल्ट इलास्टिक", mr: "4-वे हेवी ट्रॅक पँट — बेल्ट इलास्टिक" },
        description: {
          en: "A robust full-length track pant with a tapered athletic cut, drawstring waist and zipped side pockets.",
          hi: "एक मज़बूत फ़ुल-लेंथ ट्रैक पैंट, टेपर्ड एथलेटिक कट, ड्रॉस्ट्रिंग कमर और ज़िप साइड पॉकेट्स के साथ।",
          mr: "एक मजबूत फुल-लेंथ ट्रॅक पँट, टेपर्ड अ‍ॅथलेटिक कट, ड्रॉस्ट्रिंग कंबर आणि झिप साइड पॉकेट्ससह.",
        },
        details: {
          en: "A robust full-length track pant with a tapered athletic cut, drawstring waist and zipped side pockets. The heavier construction gives the silhouette a more substantial feel while retaining the flexibility expected from activewear.",
          hi: "एक मज़बूत फ़ुल-लेंथ ट्रैक पैंट, टेपर्ड एथलेटिक कट, ड्रॉस्ट्रिंग कमर और ज़िप साइड पॉकेट्स के साथ। इसकी भारी बनावट सिल्हूट को एक मज़बूत एहसास देती है, जबकि एक्टिववियर से अपेक्षित लचीलापन भी बरक़रार रहता है।",
          mr: "एक मजबूत फुल-लेंथ ट्रॅक पँट, टेपर्ड अ‍ॅथलेटिक कट, ड्रॉस्ट्रिंग कंबर आणि झिप साइड पॉकेट्ससह. याची जड रचना सिल्हूटला अधिक भक्कम अनुभव देते, तरीही अ‍ॅक्टिव्हवेअरकडून अपेक्षित लवचिकता कायम राहते.",
        },
        images: ["/products/anicy/6/1.jpg", "/products/anicy/6/2.jpg", "/products/anicy/6/3.jpg", "/products/anicy/6/4.jpg", "/products/anicy/6/5.jpg", "/products/anicy/6/6.jpg"],
      },
      {
        name: { en: "4-Way Heavy Track Pant — Machine Elastic", hi: "4-वे हैवी ट्रैक पैंट — मशीन इलास्टिक", mr: "4-वे हेवी ट्रॅक पँट — मशीन इलास्टिक" },
        description: {
          en: "A heavier-duty track pant with a clean tapered profile and elasticated waistband.",
          hi: "एक हेवी-ड्यूटी ट्रैक पैंट, साफ़ टेपर्ड प्रोफ़ाइल और इलास्टिक कमरबंद के साथ।",
          mr: "एक हेवी-ड्युटी ट्रॅक पँट, स्वच्छ टेपर्ड प्रोफाइल आणि इलास्टिक कंबरपट्ट्यासह.",
        },
        details: {
          en: "A heavier-duty track pant with a clean tapered profile and elasticated waistband. Finished with practical side storage and a minimalist sporty appearance, making it suited to training as well as everyday movement.",
          hi: "एक हेवी-ड्यूटी ट्रैक पैंट, साफ़ टेपर्ड प्रोफ़ाइल और इलास्टिक कमरबंद के साथ। प्रैक्टिकल साइड स्टोरेज और मिनिमलिस्ट स्पोर्टी लुक के साथ तैयार की गई, जो इसे ट्रेनिंग और रोज़मर्रा की गतिविधियों दोनों के लिए उपयुक्त बनाती है।",
          mr: "एक हेवी-ड्युटी ट्रॅक पँट, स्वच्छ टेपर्ड प्रोफाइल आणि इलास्टिक कंबरपट्ट्यासह. व्यावहारिक साइड स्टोरेज आणि मिनिमलिस्ट स्पोर्टी लूकसह तयार केलेली, जी हिला ट्रेनिंग आणि रोजच्या हालचालींसाठीही योग्य बनवते.",
        },
        images: ["/products/anicy/7/1.jpg", "/products/anicy/7/2.jpg", "/products/anicy/7/3.jpg", "/products/anicy/7/4.jpg", "/products/anicy/7/5.jpg", "/products/anicy/7/6.jpg"],
      },
      {
        name: { en: "4-Way Cargo Track Pant", hi: "4-वे कार्गो ट्रैक पैंट", mr: "4-वे कार्गो ट्रॅक पँट" },
        description: {
          en: "A functional cargo-inspired track pant combining a tapered athletic silhouette with multiple utility pockets.",
          hi: "एक फ़ंक्शनल कार्गो-इंस्पायर्ड ट्रैक पैंट, जो टेपर्ड एथलेटिक सिल्हूट को कई यूटिलिटी पॉकेट्स के साथ जोड़ती है।",
          mr: "एक फंक्शनल कार्गो-प्रेरित ट्रॅक पँट, जी टेपर्ड अ‍ॅथलेटिक सिल्हूटला अनेक युटिलिटी पॉकेट्ससह जोडते.",
        },
        details: {
          en: "A functional cargo-inspired track pant combining a tapered athletic silhouette with multiple utility pockets. The side cargo compartments add practicality without losing the clean, modern activewear aesthetic.",
          hi: "एक फ़ंक्शनल कार्गो-इंस्पायर्ड ट्रैक पैंट, जो टेपर्ड एथलेटिक सिल्हूट को कई यूटिलिटी पॉकेट्स के साथ जोड़ती है। साइड कार्गो कम्पार्टमेंट्स इसे व्यावहारिक बनाते हैं, वहीं साफ़-सुथरी, मॉडर्न एक्टिववियर लुक भी बनी रहती है।",
          mr: "एक फंक्शनल कार्गो-प्रेरित ट्रॅक पँट, जी टेपर्ड अ‍ॅथलेटिक सिल्हूटला अनेक युटिलिटी पॉकेट्ससह जोडते. साइड कार्गो कप्पे यामध्ये व्यावहारिकता वाढवतात, तरीही स्वच्छ, आधुनिक अ‍ॅक्टिव्हवेअर लूक कायम राहतो.",
        },
        images: ["/products/anicy/8/1.jpg", "/products/anicy/8/2.jpg", "/products/anicy/8/3.jpg", "/products/anicy/8/4.jpg", "/products/anicy/8/5.jpg", "/products/anicy/8/6.jpg"],
      },
    ],
  },
  {
    slug: "nicy",
    name: "NICY",
    logo: "/logos/nicy.png",
    accent: "#D8362B",
    segment: { en: "Girls' & ladies' wear", hi: "गर्ल्स और लेडीज़ वियर", mr: "गर्ल्स आणि लेडीज वेअर" },
    status: { en: "Active", hi: "सक्रिय", mr: "सक्रिय" },
    statusDetail: { en: "Fastest-growing", hi: "सबसे तेज़ी से बढ़ता ब्रांड", mr: "सर्वात वेगाने वाढणारा ब्रँड" },
    homeBlurb: {
      en: "Girls' and ladies' wear — our fastest-growing brand.",
      hi: "गर्ल्स और लेडीज़ वियर — हमारा सबसे तेज़ी से बढ़ता ब्रांड।",
      mr: "गर्ल्स आणि लेडीज वेअर — आमचा सर्वात वेगाने वाढणारा ब्रँड.",
    },
    description: {
      en: "Our fastest-growing brand — everyday innerwear and hosiery for girls and women, built on comfort and consistent sizing across the range.",
      hi: "हमारा सबसे तेज़ी से बढ़ता ब्रांड — लड़कियों और महिलाओं के लिए रोज़मर्रा का इननरवियर और होज़री, जो आराम और पूरी रेंज में एक जैसी साइज़िंग पर बना है।",
      mr: "आमचा सर्वात वेगाने वाढणारा ब्रँड — मुली आणि महिलांसाठी रोजचे इनरवेअर आणि होजिअरी, आराम आणि संपूर्ण रेंजमध्ये सुसंगत साइजिंगवर घडवलेला.",
    },
    products: [
      {
        name: { en: "V-Crush Plazo", hi: "वी-क्रश प्लाज़ो", mr: "व्ही-क्रश प्लाझो" },
        description: { en: "Premium V-Crush Pleated Knit (High Stretch & Zero-Iron)", hi: "प्रीमियम वी-क्रश प्लीटेड निट (हाई स्ट्रेच और ज़ीरो-आयरन)", mr: "प्रीमियम व्ही-क्रश प्लीटेड निट (हाय स्ट्रेच आणि झिरो-इस्त्री)" },
        category: "girls",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        price: "89",
        colors: [
          { name: { en: "Soft Lavender", hi: "सॉफ्ट लैवेंडर", mr: "सॉफ्ट लॅव्हेंडर" }, hex: "#C7A8E0" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#DC143C" },
          { name: { en: "Wine Burgundy", hi: "वाइन बर्गंडी", mr: "वाइन बर्गंडी" }, hex: "#722F37" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#1A1A1A" },
          { name: { en: "Deep Navy", hi: "डीप नेवी", mr: "डीप नेव्ही" }, hex: "#0B1F4B" },
          { name: { en: "Mineral Grey", hi: "मिनरल ग्रे", mr: "मिनरल ग्रे" }, hex: "#8A94A0" },
        ],
        details: { en: "Premium V-Crush Pleated Knit (High Stretch & Zero-Iron). Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम वी-क्रश प्लीटेड निट (हाई स्ट्रेच और ज़ीरो-आयरन)। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम व्ही-क्रश प्लीटेड निट (हाय स्ट्रेच आणि झिरो-इस्त्री). आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/v-crush-plazo/1.jpg"],
      },
      {
        name: { en: "2 Button Plazo", hi: "2 बटन प्लाज़ो", mr: "2 बटण प्लाझो" },
        description: { en: "Premium Pleated Lycra Accordion Knit", hi: "प्रीमियम प्लीटेड लाइक्रा एकॉर्डियन निट", mr: "प्रीमियम प्लीटेड लायक्रा अ‍ॅकॉर्डियन निट" },
        category: "girls",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        price: "98",
        colors: [
          { name: { en: "Signal Red", hi: "सिग्नल रेड", mr: "सिग्नल रेड" }, hex: "#E30B17" },
          { name: { en: "Charcoal Grey", hi: "चारकोल ग्रे", mr: "चारकोल ग्रे" }, hex: "#36454F" },
          { name: { en: "Orchid Lilac", hi: "ऑर्किड लाइलेक", mr: "ऑर्किड लायलॅक" }, hex: "#B565A7" },
          { name: { en: "Pitch Black", hi: "पिच ब्लैक", mr: "पिच ब्लॅक" }, hex: "#0D0D0D" },
          { name: { en: "Candy Pink", hi: "कैंडी पिंक", mr: "कँडी पिंक" }, hex: "#FF8DA1" },
          { name: { en: "Royal Indigo", hi: "रॉयल इंडिगो", mr: "रॉयल इंडिगो" }, hex: "#3F3D9E" },
        ],
        details: { en: "Premium Pleated Lycra Accordion Knit. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम प्लीटेड लाइक्रा एकॉर्डियन निट। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम प्लीटेड लायक्रा अ‍ॅकॉर्डियन निट. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/2-button-plazo/1.jpg"],
      },
      {
        name: { en: "Plating Plazo", hi: "प्लेटिंग प्लाज़ो", mr: "प्लेटिंग प्लाझो" },
        description: { en: "Premium Fine-Pleated Shimmer Lycra Plating Knit", hi: "प्रीमियम फ़ाइन-प्लीटेड शिमर लाइक्रा प्लेटिंग निट", mr: "प्रीमियम फाइन-प्लीटेड शिमर लायक्रा प्लेटिंग निट" },
        category: "girls",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        price: "50",
        colors: [
          { name: { en: "Slate Charcoal", hi: "स्लेट चारकोल", mr: "स्लेट चारकोल" }, hex: "#4B5259" },
          { name: { en: "Deep Amethyst", hi: "डीप एमेथिस्ट", mr: "डीप अ‍ॅमेथिस्ट" }, hex: "#6A3FA0" },
          { name: { en: "Navy Blue", hi: "नेवी ब्लू", mr: "नेव्ही ब्लू" }, hex: "#1B2A4A" },
          { name: { en: "Raven Black", hi: "रेवन ब्लैक", mr: "रेवन ब्लॅक" }, hex: "#141414" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#DC143C" },
        ],
        details: { en: "Premium Fine-Pleated Shimmer Lycra Plating Knit. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम फ़ाइन-प्लीटेड शिमर लाइक्रा प्लेटिंग निट। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम फाइन-प्लीटेड शिमर लायक्रा प्लेटिंग निट. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/plating-plazo/1.jpg"],
      },
      {
        name: { en: "Bubble Shine Plazo", hi: "बबल शाइन प्लाज़ो", mr: "बबल शाइन प्लाझो" },
        description: { en: "Premium Bubble Knit High-Drape Texture with Subdued Lustre", hi: "प्रीमियम बबल निट, हाई-ड्रेप टेक्सचर और हल्की चमक के साथ", mr: "प्रीमियम बबल निट, हाय-ड्रेप टेक्स्चर आणि सौम्य चमकसह" },
        category: "girls",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        price: "80",
        colors: [
          { name: { en: "Bright Purple", hi: "ब्राइट पर्पल", mr: "ब्राइट पर्पल" }, hex: "#8E24AA" },
          { name: { en: "Teal Blue", hi: "टील ब्लू", mr: "टील ब्लू" }, hex: "#0F6E7A" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#DC143C" },
          { name: { en: "Solid Black", hi: "सॉलिड ब्लैक", mr: "सॉलिड ब्लॅक" }, hex: "#111111" },
          { name: { en: "Maroon Plum", hi: "मरून प्लम", mr: "मरून प्लम" }, hex: "#5E2129" },
        ],
        details: { en: "Premium Bubble Knit High-Drape Texture with Subdued Lustre. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम बबल निट, हाई-ड्रेप टेक्सचर और हल्की चमक के साथ। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम बबल निट, हाय-ड्रेप टेक्स्चर आणि सौम्य चमकसह. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/bubble-shine-plazo/1.jpg"],
      },
      {
        name: { en: "6 Button Girls' Kids Pant", hi: "6 बटन गर्ल्स किड्स पैंट", mr: "6 बटण गर्ल्स किड्स पँट" },
        description: { en: "Premium Structured Twill Crepe with Tailored Front Pintuck Line", hi: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप, टेलर्ड फ्रंट पिनटक लाइन के साथ", mr: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप, टेलर्ड फ्रंट पिनटक लाइनसह" },
        category: "girls",
        collection: { en: "Contemporary Tailored Trousers", hi: "कंटेम्पररी टेलर्ड ट्राउज़र्स", mr: "कंटेम्पररी टेलर्ड ट्राउझर्स" },
        price: "120",
        colors: [
          { name: { en: "Muted Rose", hi: "म्यूटेड रोज़", mr: "म्यूटेड रोझ" }, hex: "#B98487" },
          { name: { en: "Royal Indigo", hi: "रॉयल इंडिगो", mr: "रॉयल इंडिगो" }, hex: "#3F3D9E" },
          { name: { en: "Slate Charcoal", hi: "स्लेट चारकोल", mr: "स्लेट चारकोल" }, hex: "#4B5259" },
          { name: { en: "Amethyst", hi: "एमेथिस्ट", mr: "अ‍ॅमेथिस्ट" }, hex: "#9966CC" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#DC143C" },
          { name: { en: "Midnight Blue", hi: "मिडनाइट ब्लू", mr: "मिडनाइट ब्लू" }, hex: "#191970" },
        ],
        details: { en: "Premium Structured Twill Crepe with Tailored Front Pintuck Line. Part of our Contemporary Tailored Trousers collection.", hi: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप, टेलर्ड फ्रंट पिनटक लाइन के साथ। हमारे कंटेम्पररी टेलर्ड ट्राउज़र्स कलेक्शन का हिस्सा।", mr: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप, टेलर्ड फ्रंट पिनटक लाइनसह. आमच्या कंटेम्पररी टेलर्ड ट्राउझर्स कलेक्शनचा भाग." },
        images: ["/products/nicy/6-button-kids-pant/1.jpg"],
      },
      {
        name: { en: "2 Flap Pant", hi: "2 फ्लैप पैंट", mr: "2 फ्लॅप पँट" },
        description: { en: "Premium Honeycomb Waffle Texture Knit with Buttoned Flap Accent Pockets", hi: "प्रीमियम हनीकॉम्ब वैफ़ल टेक्सचर निट, बटन वाली फ्लैप पॉकेट्स के साथ", mr: "प्रीमियम हनीकॉम्ब वॅफल टेक्स्चर निट, बटण असलेल्या फ्लॅप पॉकेट्ससह" },
        category: "girls",
        collection: { en: "Contemporary Tailored Trousers", hi: "कंटेम्पररी टेलर्ड ट्राउज़र्स", mr: "कंटेम्पररी टेलर्ड ट्राउझर्स" },
        price: "133",
        colors: [
          { name: { en: "Dusty Rose", hi: "डस्टी रोज़", mr: "डस्टी रोझ" }, hex: "#C48D9F" },
          { name: { en: "Pitch Black", hi: "पिच ब्लैक", mr: "पिच ब्लॅक" }, hex: "#0D0D0D" },
          { name: { en: "Deep Maroon", hi: "डीप मरून", mr: "डीप मरून" }, hex: "#5C1A1A" },
          { name: { en: "Charcoal Grey", hi: "चारकोल ग्रे", mr: "चारकोल ग्रे" }, hex: "#36454F" },
          { name: { en: "Royal Indigo", hi: "रॉयल इंडिगो", mr: "रॉयल इंडिगो" }, hex: "#3F3D9E" },
          { name: { en: "Soft Lilac", hi: "सॉफ्ट लाइलेक", mr: "सॉफ्ट लायलॅक" }, hex: "#D9C6EA" },
        ],
        details: { en: "Premium Honeycomb Waffle Texture Knit with Buttoned Flap Accent Pockets. Part of our Contemporary Tailored Trousers collection.", hi: "प्रीमियम हनीकॉम्ब वैफ़ल टेक्सचर निट, बटन वाली फ्लैप पॉकेट्स के साथ। हमारे कंटेम्पररी टेलर्ड ट्राउज़र्स कलेक्शन का हिस्सा।", mr: "प्रीमियम हनीकॉम्ब वॅफल टेक्स्चर निट, बटण असलेल्या फ्लॅप पॉकेट्ससह. आमच्या कंटेम्पररी टेलर्ड ट्राउझर्स कलेक्शनचा भाग." },
        images: ["/products/nicy/2-flap-pant/1.jpg"],
      },
      {
        name: { en: "Daman Print Plazo", hi: "दामन प्रिंट प्लाज़ो", mr: "दामन प्रिंट प्लाझो" },
        description: { en: "Premium Ribbed Cotton Slub with Embroidered Daman Floral Motif", hi: "प्रीमियम रिब्ड कॉटन स्लब, कढ़ाई वाले दामन फ्लोरल मोटिफ़ के साथ", mr: "प्रीमियम रिब्ड कॉटन स्लब, भरतकाम केलेल्या दामन फ्लोरल मोटिफसह" },
        category: "girls",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        price: "94",
        colors: [
          { name: { en: "Seafoam Green", hi: "सीफ़ोम ग्रीन", mr: "सीफोम ग्रीन" }, hex: "#3CB693" },
          { name: { en: "Wine Burgundy", hi: "वाइन बर्गंडी", mr: "वाइन बर्गंडी" }, hex: "#722F37" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#DC143C" },
          { name: { en: "Pitch Black", hi: "पिच ब्लैक", mr: "पिच ब्लॅक" }, hex: "#0D0D0D" },
          { name: { en: "Lavender Blue", hi: "लैवेंडर ब्लू", mr: "लॅव्हेंडर ब्लू" }, hex: "#C5B4E3" },
          { name: { en: "Deep Plum", hi: "डीप प्लम", mr: "डीप प्लम" }, hex: "#4B1E3A" },
          { name: { en: "Royal Navy", hi: "रॉयल नेवी", mr: "रॉयल नेव्ही" }, hex: "#1B2C5A" },
        ],
        details: { en: "Premium Ribbed Cotton Slub with Embroidered Daman Floral Motif. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम रिब्ड कॉटन स्लब, कढ़ाई वाले दामन फ्लोरल मोटिफ़ के साथ। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम रिब्ड कॉटन स्लब, भरतकाम केलेल्या दामन फ्लोरल मोटिफसह. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/daman-print-plazo/1.jpg"],
      },
      {
        name: { en: "Rambit Plazo", hi: "रैम्बिट प्लाज़ो", mr: "रॅम्बिट प्लाझो" },
        description: { en: "Premium Self-Textured Waffle Knit Cord with Pastel Floral Patch", hi: "प्रीमियम सेल्फ़-टेक्सचर्ड वैफ़ल निट कॉर्ड, पेस्टल फ्लोरल पैच के साथ", mr: "प्रीमियम सेल्फ-टेक्स्चर्ड वॅफल निट कॉर्ड, पेस्टल फ्लोरल पॅचसह" },
        category: "girls",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        price: "117",
        colors: [
          { name: { en: "Muted Purple", hi: "म्यूटेड पर्पल", mr: "म्यूटेड पर्पल" }, hex: "#7E57A2" },
          { name: { en: "Soft Camel", hi: "सॉफ्ट कैमल", mr: "सॉफ्ट कॅमल" }, hex: "#C6A177" },
          { name: { en: "Burgundy Wine", hi: "बर्गंडी वाइन", mr: "बर्गंडी वाइन" }, hex: "#6D1E2C" },
          { name: { en: "Classic Navy", hi: "क्लासिक नेवी", mr: "क्लासिक नेव्ही" }, hex: "#1C2841" },
          { name: { en: "Blossom Pink", hi: "ब्लॉसम पिंक", mr: "ब्लॉसम पिंक" }, hex: "#E9A6B7" },
          { name: { en: "Sage Green", hi: "सेज ग्रीन", mr: "सेज ग्रीन" }, hex: "#9CAF88" },
        ],
        details: { en: "Premium Self-Textured Waffle Knit Cord with Pastel Floral Patch. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम सेल्फ़-टेक्सचर्ड वैफ़ल निट कॉर्ड, पेस्टल फ्लोरल पैच के साथ। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम सेल्फ-टेक्स्चर्ड वॅफल निट कॉर्ड, पेस्टल फ्लोरल पॅचसह. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/rambit-plazo/1.jpg"],
      },
      {
        name: { en: "Rinkle Plazo", hi: "रिंकल प्लाज़ो", mr: "रिंकल प्लाझो" },
        description: { en: "Premium Pleated Crinkle Knit with Side Elastic Comfort Band", hi: "प्रीमियम प्लीटेड क्रिंकल निट, साइड इलास्टिक कम्फर्ट बैंड के साथ", mr: "प्रीमियम प्लीटेड क्रिंकल निट, साइड इलास्टिक कम्फर्ट बँडसह" },
        category: "girls",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        price: "94",
        colors: [
          { name: { en: "Deep Wine", hi: "डीप वाइन", mr: "डीप वाइन" }, hex: "#5E1A2E" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#1A1A1A" },
          { name: { en: "Navy Blue", hi: "नेवी ब्लू", mr: "नेव्ही ब्लू" }, hex: "#1B2A4A" },
          { name: { en: "Slate Grey", hi: "स्लेट ग्रे", mr: "स्लेट ग्रे" }, hex: "#6E7A83" },
          { name: { en: "Mustard Gold", hi: "मस्टर्ड गोल्ड", mr: "मस्टर्ड गोल्ड" }, hex: "#D4A017" },
        ],
        details: { en: "Premium Pleated Crinkle Knit with Side Elastic Comfort Band. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम प्लीटेड क्रिंकल निट, साइड इलास्टिक कम्फर्ट बैंड के साथ। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम प्लीटेड क्रिंकल निट, साइड इलास्टिक कम्फर्ट बँडसह. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/rinkle-plazo/1.jpg"],
      },
      {
        name: { en: "Swing Capri", hi: "स्विंग कैप्री", mr: "स्विंग कॅप्री" },
        description: { en: "Premium Cable-Weave Textured Soft Knit with 'Have a Good Day' Pop Patch", hi: "प्रीमियम केबल-वीव टेक्सचर्ड सॉफ़्ट निट, 'Have a Good Day' पॉप पैच के साथ", mr: "प्रीमियम केबल-विव्ह टेक्स्चर्ड सॉफ्ट निट, 'Have a Good Day' पॉप पॅचसह" },
        category: "girls",
        collection: { en: "Textured Utility & Essentials", hi: "टेक्सचर्ड यूटिलिटी और एसेंशियल्स", mr: "टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स" },
        price: "100",
        colors: [
          { name: { en: "Midnight Navy", hi: "मिडनाइट नेवी", mr: "मिडनाइट नेव्ही" }, hex: "#14213D" },
          { name: { en: "Mint Green", hi: "मिंट ग्रीन", mr: "मिंट ग्रीन" }, hex: "#9BE7C4" },
          { name: { en: "Slate Charcoal", hi: "स्लेट चारकोल", mr: "स्लेट चारकोल" }, hex: "#4B5259" },
          { name: { en: "Earth Brown", hi: "अर्थ ब्राउन", mr: "अर्थ ब्राउन" }, hex: "#6B4A32" },
          { name: { en: "Desert Sand", hi: "डेज़र्ट सैंड", mr: "डेझर्ट सँड" }, hex: "#E4B98D" },
          { name: { en: "Slate Denim", hi: "स्लेट डेनिम", mr: "स्लेट डेनिम" }, hex: "#4E6E8E" },
        ],
        details: { en: "Premium Cable-Weave Textured Soft Knit with 'Have a Good Day' Pop Patch. Part of our Textured Utility & Essentials collection.", hi: "प्रीमियम केबल-वीव टेक्सचर्ड सॉफ़्ट निट, 'Have a Good Day' पॉप पैच के साथ। हमारे टेक्सचर्ड यूटिलिटी और एसेंशियल्स कलेक्शन का हिस्सा।", mr: "प्रीमियम केबल-विव्ह टेक्स्चर्ड सॉफ्ट निट, 'Have a Good Day' पॉप पॅचसह. आमच्या टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स कलेक्शनचा भाग." },
        images: ["/products/nicy/swing-capri/1.jpg"],
      },
      {
        name: { en: "4 Pocket Cargo", hi: "4 पॉकेट कार्गो", mr: "4 पॉकेट कार्गो" },
        description: { en: "Premium Cotton Twill Utility Stretch with Side Flap Flared Pockets", hi: "प्रीमियम कॉटन ट्विल यूटिलिटी स्ट्रेच, साइड फ्लैप फ्लेयर्ड पॉकेट्स के साथ", mr: "प्रीमियम कॉटन ट्विल युटिलिटी स्ट्रेच, साइड फ्लॅप फ्लेअर्ड पॉकेट्ससह" },
        category: "girls",
        collection: { en: "Textured Utility & Essentials", hi: "टेक्सचर्ड यूटिलिटी और एसेंशियल्स", mr: "टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स" },
        price: "138",
        colors: [
          { name: { en: "Deep Plum", hi: "डीप प्लम", mr: "डीप प्लम" }, hex: "#4B1E3A" },
          { name: { en: "Blossom Pink", hi: "ब्लॉसम पिंक", mr: "ब्लॉसम पिंक" }, hex: "#E9A6B7" },
          { name: { en: "Royal Blue", hi: "रॉयल ब्लू", mr: "रॉयल ब्लू" }, hex: "#1E3A8A" },
          { name: { en: "Graphite Grey", hi: "ग्रेफाइट ग्रे", mr: "ग्रेफाइट ग्रे" }, hex: "#3A3B3C" },
          { name: { en: "Pitch Black", hi: "पिच ब्लैक", mr: "पिच ब्लॅक" }, hex: "#0D0D0D" },
        ],
        details: { en: "Premium Cotton Twill Utility Stretch with Side Flap Flared Pockets. Part of our Textured Utility & Essentials collection.", hi: "प्रीमियम कॉटन ट्विल यूटिलिटी स्ट्रेच, साइड फ्लैप फ्लेयर्ड पॉकेट्स के साथ। हमारे टेक्सचर्ड यूटिलिटी और एसेंशियल्स कलेक्शन का हिस्सा।", mr: "प्रीमियम कॉटन ट्विल युटिलिटी स्ट्रेच, साइड फ्लॅप फ्लेअर्ड पॉकेट्ससह. आमच्या टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स कलेक्शनचा भाग." },
        images: ["/products/nicy/4-pocket-cargo/1.jpg"],
      },
      {
        name: { en: "Micro Leheriya Plazo", hi: "माइक्रो लहरिया प्लाज़ो", mr: "मायक्रो लहेरिया प्लाझो" },
        description: { en: "Premium Fine-Ribbed Accordion Knit with Traditional Texture Profile", hi: "प्रीमियम फ़ाइन-रिब्ड एकॉर्डियन निट, पारंपरिक टेक्सचर प्रोफ़ाइल के साथ", mr: "प्रीमियम फाइन-रिब्ड अ‍ॅकॉर्डियन निट, पारंपरिक टेक्स्चर प्रोफाइलसह" },
        category: "girls",
        collection: { en: "Textured Utility & Essentials", hi: "टेक्सचर्ड यूटिलिटी और एसेंशियल्स", mr: "टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स" },
        price: "53",
        colors: [
          { name: { en: "Classic Navy", hi: "क्लासिक नेवी", mr: "क्लासिक नेव्ही" }, hex: "#1C2841" },
          { name: { en: "Burgundy Wine", hi: "बर्गंडी वाइन", mr: "बर्गंडी वाइन" }, hex: "#6D1E2C" },
          { name: { en: "Ruby Red", hi: "रूबी रेड", mr: "रुबी रेड" }, hex: "#9B111E" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#1A1A1A" },
          { name: { en: "Deep Violet", hi: "डीप वायलेट", mr: "डीप व्हायलेट" }, hex: "#4B1F6F" },
        ],
        details: { en: "Premium Fine-Ribbed Accordion Knit with Traditional Texture Profile. Part of our Textured Utility & Essentials collection.", hi: "प्रीमियम फ़ाइन-रिब्ड एकॉर्डियन निट, पारंपरिक टेक्सचर प्रोफ़ाइल के साथ। हमारे टेक्सचर्ड यूटिलिटी और एसेंशियल्स कलेक्शन का हिस्सा।", mr: "प्रीमियम फाइन-रिब्ड अ‍ॅकॉर्डियन निट, पारंपरिक टेक्स्चर प्रोफाइलसह. आमच्या टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स कलेक्शनचा भाग." },
        images: ["/products/nicy/micro-leheriya-plazo/1.jpg"],
      },
      {
        name: { en: "Foil Plazo", hi: "फ़ॉइल प्लाज़ो", mr: "फॉइल प्लाझो" },
        description: { en: "Premium Pinstripe Foil-Printed Shimmer Ribbed Crepe Knit", hi: "प्रीमियम पिनस्ट्राइप फ़ॉइल-प्रिंटेड शिमर रिब्ड क्रेप निट", mr: "प्रीमियम पिनस्ट्राइप फॉइल-प्रिंटेड शिमर रिब्ड क्रेप निट" },
        category: "girls",
        collection: { en: "Textured Utility & Essentials", hi: "टेक्सचर्ड यूटिलिटी और एसेंशियल्स", mr: "टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स" },
        price: "67",
        colors: [
          { name: { en: "Royal Blue", hi: "रॉयल ब्लू", mr: "रॉयल ब्लू" }, hex: "#1E3A8A" },
          { name: { en: "Rose Pink", hi: "रोज़ पिंक", mr: "रोझ पिंक" }, hex: "#E6A2B0" },
          { name: { en: "Deep Plum", hi: "डीप प्लम", mr: "डीप प्लम" }, hex: "#4B1E3A" },
          { name: { en: "Obsidian Blue", hi: "ऑब्सीडियन ब्लू", mr: "ऑब्सिडियन ब्लू" }, hex: "#1D2A3A" },
          { name: { en: "Slate Silver", hi: "स्लेट सिल्वर", mr: "स्लेट सिल्व्हर" }, hex: "#B8BEC4" },
          { name: { en: "Wheat Beige", hi: "व्हीट बेज", mr: "व्हीट बेज" }, hex: "#EAD9B4" },
        ],
        details: { en: "Premium Pinstripe Foil-Printed Shimmer Ribbed Crepe Knit. Part of our Textured Utility & Essentials collection.", hi: "प्रीमियम पिनस्ट्राइप फ़ॉइल-प्रिंटेड शिमर रिब्ड क्रेप निट। हमारे टेक्सचर्ड यूटिलिटी और एसेंशियल्स कलेक्शन का हिस्सा।", mr: "प्रीमियम पिनस्ट्राइप फॉइल-प्रिंटेड शिमर रिब्ड क्रेप निट. आमच्या टेक्स्चर्ड युटिलिटी आणि इसेन्शियल्स कलेक्शनचा भाग." },
        images: ["/products/nicy/foil-plazo/1.jpg"],
      },
      {
        name: { en: "Mario Rib Plazo", hi: "मारियो रिब प्लाज़ो", mr: "मारिओ रिब प्लाझो" },
        description: { en: "Premium Mario Rib fabric.", hi: "प्रीमियम मारियो रिब फ़ैब्रिक।", mr: "प्रीमियम मारिओ रिब फॅब्रिक." },
        category: "ladies",
        collection: { en: "Signature Rib", hi: "सिग्नेचर रिब", mr: "सिग्नेचर रिब" },
        colors: [
          { name: { en: "Dusty Blue", hi: "डस्टी ब्लू", mr: "डस्टी ब्लू" }, hex: "#638BA2" },
          { name: { en: "Black", hi: "ब्लैक", mr: "ब्लॅक" }, hex: "#1A1A1A" },
          { name: { en: "Dark Coffee", hi: "डार्क कॉफ़ी", mr: "डार्क कॉफी" }, hex: "#48281D" },
          { name: { en: "Olive Green", hi: "ऑलिव ग्रीन", mr: "ऑलिव्ह ग्रीन" }, hex: "#3A5238" },
          { name: { en: "Deep Plum", hi: "डीप प्लम", mr: "डीप प्लम" }, hex: "#5F3658" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#9C2A2A" },
        ],
        details: { en: "Premium Mario Rib fabric. Free size. Part of our Signature Rib collection.", hi: "प्रीमियम मारियो रिब फ़ैब्रिक। फ्री साइज़। हमारे सिग्नेचर रिब कलेक्शन का हिस्सा।", mr: "प्रीमियम मारिओ रिब फॅब्रिक. फ्री साइज. आमच्या सिग्नेचर रिब कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-mario-rib-plazo/1.jpg"],
      },
      {
        name: { en: "Frill Rib Plazo", hi: "फ्रिल रिब प्लाज़ो", mr: "फ्रिल रिब प्लाझो" },
        description: { en: "Premium Frill Rib fabric.", hi: "प्रीमियम फ्रिल रिब फ़ैब्रिक।", mr: "प्रीमियम फ्रिल रिब फॅब्रिक." },
        category: "ladies",
        collection: { en: "Signature Rib", hi: "सिग्नेचर रिब", mr: "सिग्नेचर रिब" },
        colors: [
          { name: { en: "Charcoal", hi: "चारकोल", mr: "चारकोल" }, hex: "#585655" },
          { name: { en: "Sage Green", hi: "सेज ग्रीन", mr: "सेज ग्रीन" }, hex: "#888E80" },
          { name: { en: "Pitch Black", hi: "पिच ब्लैक", mr: "पिच ब्लॅक" }, hex: "#111111" },
          { name: { en: "Wine Burgundy", hi: "वाइन बरगंडी", mr: "वाइन बरगंडी" }, hex: "#522530" },
          { name: { en: "Dark Chocolate", hi: "डार्क चॉकलेट", mr: "डार्क चॉकलेट" }, hex: "#46342C" },
          { name: { en: "Denim Blue", hi: "डेनिम ब्लू", mr: "डेनिम ब्लू" }, hex: "#3C5371" },
        ],
        details: { en: "Premium Frill Rib fabric. Free size. Part of our Signature Rib collection.", hi: "प्रीमियम फ्रिल रिब फ़ैब्रिक। फ्री साइज़। हमारे सिग्नेचर रिब कलेक्शन का हिस्सा।", mr: "प्रीमियम फ्रिल रिब फॅब्रिक. फ्री साइज. आमच्या सिग्नेचर रिब कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-frill-rib-plazo/1.jpg"],
      },
      {
        name: { en: "R.P Rib Plazo", hi: "आर.पी. रिब प्लाज़ो", mr: "आर.पी. रिब प्लाझो" },
        description: { en: "Premium R.P Rib fabric.", hi: "प्रीमियम आर.पी. रिब फ़ैब्रिक।", mr: "प्रीमियम आर.पी. रिब फॅब्रिक." },
        category: "ladies",
        collection: { en: "Signature Rib", hi: "सिग्नेचर रिब", mr: "सिग्नेचर रिब" },
        colors: [
          { name: { en: "Heather Grey", hi: "हेदर ग्रे", mr: "हेदर ग्रे" }, hex: "#ACACAC" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#161616" },
          { name: { en: "Peach Pink", hi: "पीच पिंक", mr: "पीच पिंक" }, hex: "#E6A09C" },
          { name: { en: "Deep Teal", hi: "डीप टील", mr: "डीप टील" }, hex: "#07475F" },
          { name: { en: "Tan Camel", hi: "टैन कैमल", mr: "टॅन कॅमल" }, hex: "#B88861" },
          { name: { en: "Radiant Orchid", hi: "रेडियंट ऑर्किड", mr: "रेडियंट ऑर्किड" }, hex: "#B967A2" },
        ],
        details: { en: "Premium R.P Rib fabric. Free size. Part of our Signature Rib collection.", hi: "प्रीमियम आर.पी. रिब फ़ैब्रिक। फ्री साइज़। हमारे सिग्नेचर रिब कलेक्शन का हिस्सा।", mr: "प्रीमियम आर.पी. रिब फॅब्रिक. फ्री साइज. आमच्या सिग्नेचर रिब कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-rp-rib-plazo/1.jpg"],
      },
      {
        name: { en: "Frill 4-Pocket Plazo", hi: "फ्रिल 4-पॉकेट प्लाज़ो", mr: "फ्रिल 4-पॉकेट प्लाझो" },
        description: { en: "Premium Ribbed Frill Cord fabric.", hi: "प्रीमियम रिब्ड फ्रिल कॉर्ड फ़ैब्रिक।", mr: "प्रीमियम रिब्ड फ्रिल कॉर्ड फॅब्रिक." },
        category: "ladies",
        collection: { en: "Signature Rib", hi: "सिग्नेचर रिब", mr: "सिग्नेचर रिब" },
        colors: [
          { name: { en: "Soft Lavender", hi: "सॉफ़्ट लैवेंडर", mr: "सॉफ्ट लॅव्हेंडर" }, hex: "#9C82B3" },
          { name: { en: "Khaki Beige", hi: "खाकी बेज", mr: "खाकी बेज" }, hex: "#AC9982" },
          { name: { en: "Classic Black", hi: "क्लासिक ब्लैक", mr: "क्लासिक ब्लॅक" }, hex: "#1C1C1C" },
          { name: { en: "Deep Burgundy", hi: "डीप बरगंडी", mr: "डीप बरगंडी" }, hex: "#581225" },
          { name: { en: "Dark Asphalt", hi: "डार्क एस्फाल्ट", mr: "डार्क अ‍ॅस्फाल्ट" }, hex: "#3E4246" },
          { name: { en: "Royal Blue", hi: "रॉयल ब्लू", mr: "रॉयल ब्लू" }, hex: "#1C4279" },
        ],
        details: { en: "Premium Ribbed Frill Cord fabric. Free size. Part of our Signature Rib collection.", hi: "प्रीमियम रिब्ड फ्रिल कॉर्ड फ़ैब्रिक। फ्री साइज़। हमारे सिग्नेचर रिब कलेक्शन का हिस्सा।", mr: "प्रीमियम रिब्ड फ्रिल कॉर्ड फॅब्रिक. फ्री साइज. आमच्या सिग्नेचर रिब कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-frill-4-pocket-plazo/1.jpg"],
      },
      {
        name: { en: "Digi Scrubber Plazo", hi: "डिजी स्क्रबर प्लाज़ो", mr: "डिजी स्क्रबर प्लाझो" },
        description: { en: "Premium Digi Scrubber fabric.", hi: "प्रीमियम डिजी स्क्रबर फ़ैब्रिक।", mr: "प्रीमियम डिजी स्क्रबर फॅब्रिक." },
        category: "ladies",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        colors: [
          { name: { en: "Lavender Wave", hi: "लैवेंडर वेव", mr: "लॅव्हेंडर वेव्ह" }, hex: "#CCACC1" },
          { name: { en: "Smiley Pink", hi: "स्माइली पिंक", mr: "स्माइली पिंक" }, hex: "#EB94B8" },
          { name: { en: "Wavy Lime", hi: "वेवी लाइम", mr: "वेव्ही लाइम" }, hex: "#90B567" },
          { name: { en: "Zebra Beige", hi: "ज़ेबरा बेज", mr: "झेब्रा बेज" }, hex: "#C3B9A2" },
          { name: { en: "Aqua Wave", hi: "एक्वा वेव", mr: "एक्वा वेव्ह" }, hex: "#4FC3DB" },
        ],
        details: { en: "Premium Digi Scrubber fabric. Free size. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम डिजी स्क्रबर फ़ैब्रिक। फ्री साइज़। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम डिजी स्क्रबर फॅब्रिक. फ्री साइज. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-digi-scrubber-plazo/1.jpg"],
      },
      {
        name: { en: "Scrubber Arrow Plazo", hi: "स्क्रबर एरो प्लाज़ो", mr: "स्क्रबर अ‍ॅरो प्लाझो" },
        description: { en: "Premium Scrubber Arrow fabric.", hi: "प्रीमियम स्क्रबर एरो फ़ैब्रिक।", mr: "प्रीमियम स्क्रबर अ‍ॅरो फॅब्रिक." },
        category: "ladies",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        colors: [
          { name: { en: "Dusty Rose", hi: "डस्टी रोज़", mr: "डस्टी रोझ" }, hex: "#CC808B" },
          { name: { en: "Sand Beige", hi: "सैंड बेज", mr: "सँड बेज" }, hex: "#DFC19A" },
          { name: { en: "Midnight Black", hi: "मिडनाइट ब्लैक", mr: "मिडनाइट ब्लॅक" }, hex: "#121212" },
          { name: { en: "Maroon Red", hi: "मैरून रेड", mr: "मरून रेड" }, hex: "#711722" },
          { name: { en: "Deep Navy", hi: "डीप नेवी", mr: "डीप नेव्ही" }, hex: "#122342" },
          { name: { en: "Rich Purple", hi: "रिच पर्पल", mr: "रिच पर्पल" }, hex: "#4D204D" },
        ],
        details: { en: "Premium Scrubber Arrow fabric. Free size. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम स्क्रबर एरो फ़ैब्रिक। फ्री साइज़। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम स्क्रबर अ‍ॅरो फॅब्रिक. फ्री साइज. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-scrubber-arrow-plazo/1.jpg"],
      },
      {
        name: { en: "Print Pleated Plazo", hi: "प्रिंट प्लीटेड प्लाज़ो", mr: "प्रिंट प्लीटेड प्लाझो" },
        description: { en: "Premium Printed Crinkle fabric.", hi: "प्रीमियम प्रिंटेड क्रिंकल फ़ैब्रिक।", mr: "प्रीमियम प्रिंटेड क्रिंकल फॅब्रिक." },
        category: "ladies",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        colors: [
          { name: { en: "Deep Purple", hi: "डीप पर्पल", mr: "डीप पर्पल" }, hex: "#552861" },
          { name: { en: "Black Print", hi: "ब्लैक प्रिंट", mr: "ब्लॅक प्रिंट" }, hex: "#1A1A1A" },
          { name: { en: "Maroon Print", hi: "मैरून प्रिंट", mr: "मरून प्रिंट" }, hex: "#6B1725" },
          { name: { en: "Navy Blue Print", hi: "नेवी ब्लू प्रिंट", mr: "नेव्ही ब्लू प्रिंट" }, hex: "#162548" },
          { name: { en: "Wine Print", hi: "वाइन प्रिंट", mr: "वाइन प्रिंट" }, hex: "#58152E" },
          { name: { en: "Grey Print", hi: "ग्रे प्रिंट", mr: "ग्रे प्रिंट" }, hex: "#7B828B" },
          { name: { en: "Beige Print", hi: "बेज प्रिंट", mr: "बेज प्रिंट" }, hex: "#CFB59A" },
        ],
        details: { en: "Premium Printed Crinkle fabric. Free size. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम प्रिंटेड क्रिंकल फ़ैब्रिक। फ्री साइज़। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम प्रिंटेड क्रिंकल फॅब्रिक. फ्री साइज. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-print-pleated-plazo/1.jpg"],
      },
      {
        name: { en: "Plating Print Plazo", hi: "प्लेटिंग प्रिंट प्लाज़ो", mr: "प्लेटिंग प्रिंट प्लाझो" },
        description: { en: "Premium Printed Silk Plating fabric.", hi: "प्रीमियम प्रिंटेड सिल्क प्लेटिंग फ़ैब्रिक।", mr: "प्रीमियम प्रिंटेड सिल्क प्लेटिंग फॅब्रिक." },
        category: "ladies",
        collection: { en: "Printed & Decorative Flair", hi: "प्रिंटेड और डेकोरेटिव फ्लेयर", mr: "प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर" },
        colors: [
          { name: { en: "Royal Blue", hi: "रॉयल ब्लू", mr: "रॉयल ब्लू" }, hex: "#1753A4" },
          { name: { en: "Ruby Red", hi: "रूबी रेड", mr: "रुबी रेड" }, hex: "#B50930" },
          { name: { en: "Ivory White", hi: "आइवरी व्हाइट", mr: "आयव्हरी व्हाइट" }, hex: "#F4ECEC" },
          { name: { en: "Midnight Black", hi: "मिडनाइट ब्लैक", mr: "मिडनाइट ब्लॅक" }, hex: "#161A20" },
          { name: { en: "Peach Cream", hi: "पीच क्रीम", mr: "पीच क्रीम" }, hex: "#F1CC9C" },
          { name: { en: "Rich Purple", hi: "रिच पर्पल", mr: "रिच पर्पल" }, hex: "#6B1271" },
        ],
        details: { en: "Premium Printed Silk Plating fabric. Free size. Part of our Printed & Decorative Flair collection.", hi: "प्रीमियम प्रिंटेड सिल्क प्लेटिंग फ़ैब्रिक। फ्री साइज़। हमारे प्रिंटेड और डेकोरेटिव फ्लेयर कलेक्शन का हिस्सा।", mr: "प्रीमियम प्रिंटेड सिल्क प्लेटिंग फॅब्रिक. फ्री साइज. आमच्या प्रिंटेड आणि डेकोरेटिव्ह फ्लेअर कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-plating-print-plazo/1.jpg"],
      },
      {
        name: { en: "Heavy Platting Plazo", hi: "हैवी प्लेटिंग प्लाज़ो", mr: "हेवी प्लेटिंग प्लाझो" },
        description: { en: "Premium Heavy Platting fabric.", hi: "प्रीमियम हैवी प्लेटिंग फ़ैब्रिक।", mr: "प्रीमियम हेवी प्लेटिंग फॅब्रिक." },
        category: "ladies",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        colors: [
          { name: { en: "Steel Blue", hi: "स्टील ब्लू", mr: "स्टील ब्लू" }, hex: "#7194A4" },
          { name: { en: "Royal Indigo", hi: "रॉयल इंडिगो", mr: "रॉयल इंडिगो" }, hex: "#164471" },
          { name: { en: "Pistachio", hi: "पिस्ता", mr: "पिस्ता" }, hex: "#91A86B" },
          { name: { en: "Pastel Pink", hi: "पेस्टल पिंक", mr: "पेस्टल पिंक" }, hex: "#EE9096" },
          { name: { en: "Dark Maroon", hi: "डार्क मैरून", mr: "डार्क मरून" }, hex: "#5D1520" },
          { name: { en: "Slate Grey", hi: "स्लेट ग्रे", mr: "स्लेट ग्रे" }, hex: "#485058" },
        ],
        details: { en: "Premium Heavy Platting fabric. Free size. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम हैवी प्लेटिंग फ़ैब्रिक। फ्री साइज़। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम हेवी प्लेटिंग फॅब्रिक. फ्री साइज. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-heavy-platting-plazo/1.jpg"],
      },
      {
        name: { en: "2 Button Plazo", hi: "2 बटन प्लाज़ो", mr: "2 बटण प्लाझो" },
        description: { en: "Premium Pleated Lycra fabric.", hi: "प्रीमियम प्लीटेड लाइक्रा फ़ैब्रिक।", mr: "प्रीमियम प्लीटेड लायक्रा फॅब्रिक." },
        category: "ladies",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        colors: [
          { name: { en: "Plum Wine", hi: "प्लम वाइन", mr: "प्लम वाइन" }, hex: "#5D1C4A" },
          { name: { en: "Midnight Navy", hi: "मिडनाइट नेवी", mr: "मिडनाइट नेव्ही" }, hex: "#162344" },
          { name: { en: "Charcoal Grey", hi: "चारकोल ग्रे", mr: "चारकोल ग्रे" }, hex: "#424244" },
          { name: { en: "Blush Pink", hi: "ब्लश पिंक", mr: "ब्लश पिंक" }, hex: "#E69CB5" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#1C1A1C" },
        ],
        details: { en: "Premium Pleated Lycra fabric. Free size. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम प्लीटेड लाइक्रा फ़ैब्रिक। फ्री साइज़। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम प्लीटेड लायक्रा फॅब्रिक. फ्री साइज. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-2-button-plazo/1.jpg"],
      },
      {
        name: { en: "Bubble 1-Pocket Plazo", hi: "बबल 1-पॉकेट प्लाज़ो", mr: "बबल 1-पॉकेट प्लाझो" },
        description: { en: "Premium Bubble Knit Texture fabric.", hi: "प्रीमियम बबल निट टेक्सचर फ़ैब्रिक।", mr: "प्रीमियम बबल निट टेक्स्चर फॅब्रिक." },
        category: "ladies",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        colors: [
          { name: { en: "Denim Blue", hi: "डेनिम ब्लू", mr: "डेनिम ब्लू" }, hex: "#424F7B" },
          { name: { en: "Solid Black", hi: "सॉलिड ब्लैक", mr: "सॉलिड ब्लॅक" }, hex: "#161616" },
          { name: { en: "Bright Purple", hi: "ब्राइट पर्पल", mr: "ब्राइट पर्पल" }, hex: "#6B1F82" },
          { name: { en: "Magenta Orchid", hi: "मैजेंटा ऑर्किड", mr: "मॅजेंटा ऑर्किड" }, hex: "#A0177B" },
          { name: { en: "Fiery Red", hi: "फ़ायरी रेड", mr: "फायरी रेड" }, hex: "#CC112A" },
        ],
        details: { en: "Premium Bubble Knit Texture fabric. Free size. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम बबल निट टेक्सचर फ़ैब्रिक। फ्री साइज़। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम बबल निट टेक्स्चर फॅब्रिक. फ्री साइज. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-bubble-1-pocket-plazo/1.jpg"],
      },
      {
        name: { en: "V-Crush 1-Pocket Plazo", hi: "वी-क्रश 1-पॉकेट प्लाज़ो", mr: "व्ही-क्रश 1-पॉकेट प्लाझो" },
        description: { en: "Premium V-Crush Pleated Knit fabric.", hi: "प्रीमियम वी-क्रश प्लीटेड निट फ़ैब्रिक।", mr: "प्रीमियम व्ही-क्रश प्लीटेड निट फॅब्रिक." },
        category: "ladies",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        colors: [
          { name: { en: "Deep Plum", hi: "डीप प्लम", mr: "डीप प्लम" }, hex: "#5D1755" },
          { name: { en: "Blush Pink", hi: "ब्लश पिंक", mr: "ब्लश पिंक" }, hex: "#DFA0B8" },
          { name: { en: "Midnight Navy", hi: "मिडनाइट नेवी", mr: "मिडनाइट नेव्ही" }, hex: "#1C2A46" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#121212" },
          { name: { en: "Soft Lilac", hi: "सॉफ़्ट लिलाक", mr: "सॉफ्ट लिलाक" }, hex: "#A482B5" },
          { name: { en: "Slate Blue", hi: "स्लेट ब्लू", mr: "स्लेट ब्लू" }, hex: "#526382" },
        ],
        details: { en: "Premium V-Crush Pleated Knit fabric. Free size. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम वी-क्रश प्लीटेड निट फ़ैब्रिक। फ्री साइज़। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम व्ही-क्रश प्लीटेड निट फॅब्रिक. फ्री साइज. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-vcrush-1-pocket-plazo/1.jpg"],
      },
      {
        name: { en: "Micro Khajuri Plazo", hi: "माइक्रो खजूरी प्लाज़ो", mr: "मायक्रो खजुरी प्लाझो" },
        description: { en: "Premium Micro-Chevron Khajuri Knit fabric.", hi: "प्रीमियम माइक्रो-शेवरॉन खजूरी निट फ़ैब्रिक।", mr: "प्रीमियम मायक्रो-शेव्ह्रॉन खजुरी निट फॅब्रिक." },
        category: "ladies",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        colors: [
          { name: { en: "Royal Purple", hi: "रॉयल पर्पल", mr: "रॉयल पर्पल" }, hex: "#5F1C79" },
          { name: { en: "Raven Black", hi: "रैवन ब्लैक", mr: "रॅव्हन ब्लॅक" }, hex: "#121212" },
          { name: { en: "Steel Grey", hi: "स्टील ग्रे", mr: "स्टील ग्रे" }, hex: "#5B666F" },
          { name: { en: "Indigo Violet", hi: "इंडिगो वायलेट", mr: "इंडिगो व्हायोलेट" }, hex: "#423E85" },
          { name: { en: "Crimson Red", hi: "क्रिमसन रेड", mr: "क्रिमसन रेड" }, hex: "#B8122E" },
        ],
        details: { en: "Premium Micro-Chevron Khajuri Knit fabric. Free size. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम माइक्रो-शेवरॉन खजूरी निट फ़ैब्रिक। फ्री साइज़। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम मायक्रो-शेव्ह्रॉन खजुरी निट फॅब्रिक. फ्री साइज. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-micro-khajuri-plazo/1.jpg"],
      },
      {
        name: { en: "Jacquard Palazzo", hi: "जैक्वार्ड पलाज़ो", mr: "जॅकार्ड पलाझो" },
        description: { en: "Premium Textured Jacquard Knit fabric.", hi: "प्रीमियम टेक्सचर्ड जैक्वार्ड निट फ़ैब्रिक।", mr: "प्रीमियम टेक्स्चर्ड जॅकार्ड निट फॅब्रिक." },
        category: "ladies",
        collection: { en: "Premium Knits & Pleated Luxury", hi: "प्रीमियम निट्स और प्लीटेड लक्ज़री", mr: "प्रीमियम निट्स आणि प्लीटेड लक्झरी" },
        colors: [
          { name: { en: "Rani Pink", hi: "रानी पिंक", mr: "राणी पिंक" }, hex: "#DF166C" },
          { name: { en: "Dark Grey", hi: "डार्क ग्रे", mr: "डार्क ग्रे" }, hex: "#393E46" },
          { name: { en: "Solid Black", hi: "सॉलिड ब्लैक", mr: "सॉलिड ब्लॅक" }, hex: "#121212" },
          { name: { en: "Wine Maroon", hi: "वाइन मैरून", mr: "वाइन मरून" }, hex: "#52122A" },
          { name: { en: "Navy Blue", hi: "नेवी ब्लू", mr: "नेव्ही ब्लू" }, hex: "#152244" },
          { name: { en: "Teal Green", hi: "टील ग्रीन", mr: "टील ग्रीन" }, hex: "#085269" },
        ],
        details: { en: "Premium Textured Jacquard Knit fabric. Free size. Part of our Premium Knits & Pleated Luxury collection.", hi: "प्रीमियम टेक्सचर्ड जैक्वार्ड निट फ़ैब्रिक। फ्री साइज़। हमारे प्रीमियम निट्स और प्लीटेड लक्ज़री कलेक्शन का हिस्सा।", mr: "प्रीमियम टेक्स्चर्ड जॅकार्ड निट फॅब्रिक. फ्री साइज. आमच्या प्रीमियम निट्स आणि प्लीटेड लक्झरी कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-jacquard-palazzo/1.jpg"],
      },
      {
        name: { en: "Pintex 1-Pocket Plazo", hi: "पिनटक्स 1-पॉकेट प्लाज़ो", mr: "पिनटक्स 1-पॉकेट प्लाझो" },
        description: { en: "Premium Heavy Pintex Crepe fabric.", hi: "प्रीमियम हैवी पिनटक्स क्रेप फ़ैब्रिक।", mr: "प्रीमियम हेवी पिनटक्स क्रेप फॅब्रिक." },
        category: "ladies",
        collection: { en: "Contemporary Tailored Trousers", hi: "कंटेम्पररी टेलर्ड ट्राउज़र्स", mr: "कंटेम्पररी टेलर्ड ट्राउझर्स" },
        colors: [
          { name: { en: "Muted Brown", hi: "म्यूटेड ब्राउन", mr: "म्यूटेड ब्राऊन" }, hex: "#8B6F5F" },
          { name: { en: "Solid Black", hi: "सॉलिड ब्लैक", mr: "सॉलिड ब्लॅक" }, hex: "#1A1A1A" },
          { name: { en: "Navy Blue", hi: "नेवी ब्लू", mr: "नेव्ही ब्लू" }, hex: "#253453" },
          { name: { en: "Asphalt Grey", hi: "एस्फाल्ट ग्रे", mr: "अ‍ॅस्फाल्ट ग्रे" }, hex: "#50535B" },
          { name: { en: "Bright Purple", hi: "ब्राइट पर्पल", mr: "ब्राइट पर्पल" }, hex: "#612886" },
          { name: { en: "Deep Red", hi: "डीप रेड", mr: "डीप रेड" }, hex: "#AC1122" },
        ],
        details: { en: "Premium Heavy Pintex Crepe fabric. Free size. Part of our Contemporary Tailored Trousers collection.", hi: "प्रीमियम हैवी पिनटक्स क्रेप फ़ैब्रिक। फ्री साइज़। हमारे कंटेम्पररी टेलर्ड ट्राउज़र्स कलेक्शन का हिस्सा।", mr: "प्रीमियम हेवी पिनटक्स क्रेप फॅब्रिक. फ्री साइज. आमच्या कंटेम्पररी टेलर्ड ट्राउझर्स कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-pintex-1-pocket-plazo/1.jpg"],
      },
      {
        name: { en: "4 Pocket Cargo Pant", hi: "4 पॉकेट कार्गो पैंट", mr: "4 पॉकेट कार्गो पँट" },
        description: { en: "Premium Cotton Twill Stretch fabric.", hi: "प्रीमियम कॉटन ट्विल स्ट्रेच फ़ैब्रिक।", mr: "प्रीमियम कॉटन ट्विल स्ट्रेच फॅब्रिक." },
        category: "ladies",
        collection: { en: "Contemporary Tailored Trousers", hi: "कंटेम्पररी टेलर्ड ट्राउज़र्स", mr: "कंटेम्पररी टेलर्ड ट्राउझर्स" },
        colors: [
          { name: { en: "Signal Red", hi: "सिग्नल रेड", mr: "सिग्नल रेड" }, hex: "#CC1222" },
          { name: { en: "Deep Navy", hi: "डीप नेवी", mr: "डीप नेव्ही" }, hex: "#1A223A" },
          { name: { en: "Pitch Black", hi: "पिच ब्लैक", mr: "पिच ब्लॅक" }, hex: "#121212" },
          { name: { en: "Slate Grey", hi: "स्लेट ग्रे", mr: "स्लेट ग्रे" }, hex: "#53585F" },
        ],
        details: { en: "Premium Cotton Twill Stretch fabric. Free size. Part of our Contemporary Tailored Trousers collection.", hi: "प्रीमियम कॉटन ट्विल स्ट्रेच फ़ैब्रिक। फ्री साइज़। हमारे कंटेम्पररी टेलर्ड ट्राउज़र्स कलेक्शन का हिस्सा।", mr: "प्रीमियम कॉटन ट्विल स्ट्रेच फॅब्रिक. फ्री साइज. आमच्या कंटेम्पररी टेलर्ड ट्राउझर्स कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-4-pocket-cargo-pant/1.jpg"],
      },
      {
        name: { en: "6 Button Plazo Pant", hi: "6 बटन प्लाज़ो पैंट", mr: "6 बटण प्लाझो पँट" },
        description: { en: "Premium Structured Twill Crepe fabric.", hi: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप फ़ैब्रिक।", mr: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप फॅब्रिक." },
        category: "ladies",
        collection: { en: "Contemporary Tailored Trousers", hi: "कंटेम्पररी टेलर्ड ट्राउज़र्स", mr: "कंटेम्पररी टेलर्ड ट्राउझर्स" },
        colors: [
          { name: { en: "Lilac Purple", hi: "लिलाक पर्पल", mr: "लिलाक पर्पल" }, hex: "#A492C5" },
          { name: { en: "Jet Black", hi: "जेट ब्लैक", mr: "जेट ब्लॅक" }, hex: "#1A1A1A" },
          { name: { en: "Soft Camel", hi: "सॉफ़्ट कैमल", mr: "सॉफ्ट कॅमल" }, hex: "#C39A77" },
          { name: { en: "Deep Wine", hi: "डीप वाइन", mr: "डीप वाइन" }, hex: "#6D0928" },
          { name: { en: "Teal Blue", hi: "टील ब्लू", mr: "टील ब्लू" }, hex: "#164A6D" },
          { name: { en: "Slate Grey", hi: "स्लेट ग्रे", mr: "स्लेट ग्रे" }, hex: "#5D6971" },
        ],
        details: { en: "Premium Structured Twill Crepe fabric. Free size. Part of our Contemporary Tailored Trousers collection.", hi: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप फ़ैब्रिक। फ्री साइज़। हमारे कंटेम्पररी टेलर्ड ट्राउज़र्स कलेक्शन का हिस्सा।", mr: "प्रीमियम स्ट्रक्चर्ड ट्विल क्रेप फॅब्रिक. फ्री साइज. आमच्या कंटेम्पररी टेलर्ड ट्राउझर्स कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-6-button-plazo-pant/1.jpg"],
      },
      {
        name: { en: "Korean 2 Pocket Pant", hi: "कोरियन 2 पॉकेट पैंट", mr: "कोरियन 2 पॉकेट पँट" },
        description: { en: "Premium Korean Import Gabardine Stretch fabric.", hi: "प्रीमियम कोरियन इम्पोर्ट गैबार्डिन स्ट्रेच फ़ैब्रिक।", mr: "प्रीमियम कोरियन इम्पोर्ट गॅबार्डिन स्ट्रेच फॅब्रिक." },
        category: "ladies",
        collection: { en: "Contemporary Tailored Trousers", hi: "कंटेम्पररी टेलर्ड ट्राउज़र्स", mr: "कंटेम्पररी टेलर्ड ट्राउझर्स" },
        colors: [
          { name: { en: "Classic Tan/Brown", hi: "क्लासिक टैन/ब्राउन", mr: "क्लासिक टॅन/ब्राऊन" }, hex: "#8B5B3E" },
          { name: { en: "Soft Light Grey", hi: "सॉफ़्ट लाइट ग्रे", mr: "सॉफ्ट लाइट ग्रे" }, hex: "#C1C5CC" },
          { name: { en: "Olive Khaki", hi: "ऑलिव खाकी", mr: "ऑलिव्ह खाकी" }, hex: "#4D523E" },
          { name: { en: "Deep Navy", hi: "डीप नेवी", mr: "डीप नेव्ही" }, hex: "#1C2238" },
          { name: { en: "Midnight Black", hi: "मिडनाइट ब्लैक", mr: "मिडनाइट ब्लॅक" }, hex: "#121212" },
          { name: { en: "Asphalt Charcoal", hi: "एस्फाल्ट चारकोल", mr: "अ‍ॅस्फाल्ट चारकोल" }, hex: "#4F5255" },
        ],
        details: { en: "Premium Korean Import Gabardine Stretch fabric. Free size. Part of our Contemporary Tailored Trousers collection.", hi: "प्रीमियम कोरियन इम्पोर्ट गैबार्डिन स्ट्रेच फ़ैब्रिक। फ्री साइज़। हमारे कंटेम्पररी टेलर्ड ट्राउज़र्स कलेक्शन का हिस्सा।", mr: "प्रीमियम कोरियन इम्पोर्ट गॅबार्डिन स्ट्रेच फॅब्रिक. फ्री साइज. आमच्या कंटेम्पररी टेलर्ड ट्राउझर्स कलेक्शनचा भाग." },
        images: ["/products/nicy/ladies-korean-2-pocket-pant/1.jpg"],
      },
    ],
  },
  {
    slug: "avron",
    name: "Avron",
    logo: "/logos/avron.png",
    accent: "#5b6470",
    segment: { en: "Premium men's performance wear", hi: "प्रीमियम मेन्स परफॉर्मेंस वियर", mr: "प्रीमियम मेन्स परफॉर्मन्स वेअर" },
    status: { en: "Launching soon", hi: "जल्द लॉन्च हो रहा है", mr: "लवकरच लाँच होत आहे" },
    statusDetail: { en: "In development", hi: "निर्माणाधीन", mr: "विकासाधीन" },
    homeBlurb: {
      en: "Premium men's performance wear.",
      hi: "प्रीमियम मेन्स परफॉर्मेंस वियर।",
      mr: "प्रीमियम मेन्स परफॉर्मन्स वेअर.",
    },
    description: { en: null, hi: null, mr: null },
    comingSoon: {
      tag: { en: "Launching soon", hi: "जल्द लॉन्च हो रहा है", mr: "लवकरच लाँच होत आहे" },
      heading: {
        en: "Our newest brand — a premium step up in men's performance wear.",
        hi: "हमारा सबसे नया ब्रांड — मेन्स परफॉर्मेंस वियर में एक प्रीमियम कदम आगे।",
        mr: "आमचा सर्वात नवीन ब्रँड — मेन्स परफॉर्मन्स वेअरमधील एक प्रीमियम पाऊल पुढे.",
      },
      copy: {
        en: "Avron is currently in development, with packaging and launch details being finalised. Full product listings will go live closer to launch — check back soon, or ask us directly for early details.",
        hi: "Avron फ़िलहाल निर्माणाधीन है, पैकेजिंग और लॉन्च की जानकारी अंतिम रूप ले रही है। पूरी प्रोडक्ट लिस्टिंग लॉन्च के करीब लाइव होगी — जल्द फिर देखें, या शुरुआती जानकारी के लिए सीधे हमसे पूछें।",
        mr: "Avron सध्या विकासाधीन आहे, पॅकेजिंग आणि लाँचचे तपशील अंतिम केले जात आहेत. संपूर्ण प्रोडक्ट लिस्टिंग लाँचच्या जवळ लाइव्ह होईल — लवकरच पुन्हा पहा, किंवा सुरुवातीच्या माहितीसाठी थेट आम्हाला विचारा.",
      },
    },
    products: [],
  },
];

function pick(field, locale) {
  if (field === null || field === undefined) return field;
  if (typeof field === "object" && !Array.isArray(field)) {
    return field[locale] ?? field.en ?? null;
  }
  return field;
}

function resolveProduct(product, locale) {
  return {
    ...product,
    name: pick(product.name, locale),
    description: pick(product.description, locale),
    details: pick(product.details, locale),
    colors: product.colors
      ? product.colors.map((c) => ({ name: pick(c.name, locale), hex: c.hex }))
      : undefined,
  };
}

function resolveBrand(brand, locale) {
  const resolved = {
    ...brand,
    segment: pick(brand.segment, locale),
    status: pick(brand.status, locale),
    statusDetail: pick(brand.statusDetail, locale),
    homeBlurb: pick(brand.homeBlurb, locale),
    description: pick(brand.description, locale),
    products: brand.products.map((p) => resolveProduct(p, locale)),
  };
  if (brand.comingSoon) {
    resolved.comingSoon = {
      tag: pick(brand.comingSoon.tag, locale),
      heading: pick(brand.comingSoon.heading, locale),
      copy: pick(brand.comingSoon.copy, locale),
    };
  }
  return resolved;
}

export function getBrands(locale = "en") {
  return BRANDS_RAW.map((b) => resolveBrand(b, locale));
}

export function getBrand(slug, locale = "en") {
  const raw = BRANDS_RAW.find((b) => b.slug === slug);
  return raw ? resolveBrand(raw, locale) : undefined;
}
